### ISSUE TITLE
Console.logs

### ISSUE THREAD

**Issue by njsfield** [esraajb/oh-auth#39]
Please remove
https://github.com/esraajb/oh-auth/blob/master/src/routes/results.route.js#L34
https://github.com/esraajb/oh-auth/blob/master/src/routes/results.route.js#L41
https://github.com/esraajb/oh-auth/blob/master/src/routes/results.route.js#L42

**Comment by msachi** [comment]
Also uncommented code! ☺️

**Comment by RhodesPeter** [comment]
I have deleted the first point  `algorithm': 'HS256` - I believe this is optional as HS256 is the default if you don't specify otherwise. 

When I remove the other two pieces of code it all stops working so I am going to pass on these two. 

I have removed the uncommented code too.
